language: scala
jdk:
- oraclejdk8
scala:
- 2.11.12
- 2.12.8

before_install:
- git fetch --tags
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

install:
- pip install --user codecov
script: sbt ++$TRAVIS_SCALA_VERSION validate
after_success:
- codecov

stages:
- name: test
- name: release
  if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
  - stage: release
    script: sbt ci-release
